"""s6-t3: repository hygiene scan (report only, fixes nothing).

1. Tracked files matching  _426 | old_ucs | scratch/.*parquet  (case-insensitive), as
   `git ls-files | grep -iE "_426|old_ucs|scratch/.*parquet"`.
2. Tracked Python files containing an absolute Windows or home path
   (D:\\, D:/, C:\\Users, C:/Users, /home/, /Users/).
3. Tracked Python files that reference a data/model file (string literal ending in .parquet, .csv,
   .pt, .pkl, .npz, .json, .yaml) whose repo-relative path is not tracked, after trying the literal
   relative to the repo root and to the script's directory and its parents. This is a heuristic:
   a hit means "probably depends on an uncommitted file"; files written by the script itself also match.
Writes docs/hygiene/hygiene_scan.json. Run from the repository root.
"""
import json
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ABS = re.compile(r"""(?i)(['"])(?:[a-z]:[\\/](?!/)|/home/|/users/)[^'"]*\1""")
LIT = re.compile(r"""['"]([A-Za-z0-9_./\\-]+\.(?:parquet|csv|pt|pkl|npz|json|yaml|yml))['"]""")


def main():
    files = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True).stdout.splitlines()
    tracked = set(files)
    pattern = re.compile(r"(?i)_426|old_ucs|scratch/.*parquet")
    matches = [f for f in files if pattern.search(f)]

    abs_hits, missing = {}, {}
    for f in files:
        if not f.endswith(".py"):
            continue
        try:
            text = (REPO / f).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        # record only the kind of absolute path (drive / home prefix), not the full path
        a = sorted({re.sub(r"(?i)^(['\"])((?:[a-z]:[\\/](?:users[\\/])?)|/home/|/users/).*$", r"\2…", m.group(0))
                    for m in ABS.finditer(text)})
        if a:
            abs_hits[f] = a[:10]
        bases = [Path(f).parent] + list(Path(f).parents)
        miss = []
        for lit in sorted({m.group(1).replace("\\", "/") for m in LIT.finditer(text)}):
            if lit.startswith("/") or ":" in lit:
                continue
            cands = {(b / lit).as_posix().lstrip("./") for b in bases} | {lit.lstrip("./")}
            cands = {c[2:] if c.startswith("./") else c for c in cands}
            if not any(c in tracked for c in cands):
                miss.append(lit)
        if miss:
            missing[f] = miss[:15]

    out = {"generated_by": "docs/hygiene/hygiene_scan.py",
           "tracked_files_matching_426_old_ucs_scratch_parquet": matches,
           "python_files_with_absolute_paths": abs_hits,
           "python_files_referencing_untracked_data_files": missing}
    (REPO / "docs/hygiene/hygiene_scan.json").write_text(json.dumps(out, indent=2) + "\n")
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True, text=True).stdout.strip()
    base = subprocess.run(["git", "rev-parse", "--short", "origin/main"], cwd=REPO, capture_output=True, text=True).stdout.strip()
    md = ["# Repository Hygiene Report", "",
          f"Report only; nothing was fixed. Generated by `docs/hygiene/hygiene_scan.py` at `{head}`, whose code is "
          f"main `{base}` plus documentation changes only (full lists in `docs/hygiene/hygiene_scan.json`). "
          "Absolute paths are shown only by their prefix.", "",
          "## 1. Tracked files matching `_426|old_ucs|scratch/.*parquet`", "",
          "`git ls-files | grep -iE \"_426|old_ucs|scratch/.*parquet\"`: " + (", ".join(f"`{m}`" for m in matches) or "**none**"), "",
          f"## 2. Python files with absolute paths ({len(abs_hits)})", "", "| File | Absolute path(s) |", "|---|---|"]
    md += [f"| `{f}` | {'; '.join('`' + p.strip(chr(34) + chr(39)) + '`' for p in a)} |" for f, a in abs_hits.items()]
    md += ["", f"## 3. Python files that probably depend on an uncommitted file ({len(missing)})", "",
           "Heuristic: a string literal naming a .parquet/.csv/.pt/.pkl/.npz/.json/.yaml path that is not tracked "
           "relative to the repo root or the script's folders. Output files the script writes itself also match.", "",
           "| File | Untracked path literal(s) |", "|---|---|"]
    md += [f"| `{f}` | {', '.join('`' + x + '`' for x in m)} |" for f, m in missing.items()]
    merge_md = REPO / "docs/hygiene/merge_test.md"  # written by hand from the s6-t4 test run
    md += ["", "## 4. feature/dashboard-risk-ui merge test", "",
           merge_md.read_text(encoding="utf-8").strip() if merge_md.exists() else "pending: s6-t4", ""]
    (REPO / "docs/HYGIENE_REPORT.md").write_text("\n".join(md), encoding="utf-8")
    print(len(matches), len(abs_hits), len(missing))


if __name__ == "__main__":
    main()
