"""
SHADOWCAT SOC Cockpit - Page 7: Validation & Trust
Validation numbers come only from frontend/models/loeo_37fold_results.json, which is generated by
frontend/scripts/build_validation_json.py from committed sidecar / benchmark files.
Audit-chain entries come from backend/audit_chain.json.
"""

import hashlib
import html
from pathlib import Path

import pandas as pd
import streamlit as st
from styles import TOKENS, render_html
from data_provider import get_validation_data, get_audit_chain_status, get_live_notarization_status

REPO_ROOT = Path(__file__).resolve().parents[2]
PROVENANCE_FILES = [
    "ml1/artifacts/lstm/gaussian_next_state_best_v3_packetcov.pt",
    "ml1/artifacts/lstm/stage_head_v3/reeval_packetcov/stage_head_best.pt",
]


@st.cache_data(show_spinner=False)
def _sha256(rel_path: str) -> str:
    p = REPO_ROOT / rel_path
    if not p.is_file():
        return "file not present"
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _f(x, nd=4):
    return "—" if x is None else f"{x:.{nd}f}"


def render_page():
    t = TOKENS.get(st.session_state.get("theme", "dark"), TOKENS["dark"])
    val = get_validation_data()
    tasks = val.get("tasks", {})

    render_html(f"""
    <div class="soc-card" style="margin-bottom: 1rem;">
        <span style="font-family: 'JetBrains Mono', monospace; font-size: 1.25rem; font-weight: 700; color: {t['text_high']}; text-transform: uppercase;">
            Validation &amp; Trust
        </span>
        <div style="font-family: 'Inter', sans-serif; font-size: 0.78rem; color: {t['text_secondary']}; margin-top: 0.3rem;">
            {html.escape(val.get('protocol', ''))}. Source: <code>{html.escape(val.get('generated_by', ''))}</code>
        </div>
    </div>
    """)

    if not tasks:
        st.warning("frontend/models/loeo_37fold_results.json is missing. Run frontend/scripts/build_validation_json.py.")
        return

    # 1. Mean over 37 LOEO folds
    rows = ""
    for task, d in tasks.items():
        for name, m in (("Stacked calibrated LSTM", d["stacked_mean"]), ("Logistic regression baseline", d["lr_mean"])):
            rows += (f"<tr><td>{task} ({html.escape(d['target'])})</td><td>{name}</td>"
                     f"<td><b>{_f(m['f1'])}</b></td><td>{_f(m['precision'])}</td><td>{_f(m['recall'])}</td>"
                     f"<td>{_f(m['fpr'])}</td><td>{_f(m['roc_auc'])}</td></tr>")
    det = tasks.get("detection", {})
    lr_note = ""
    if det:
        zero = ", ".join(str(f) for f in det["lr_folds_f1_eq_0"]) or "none"
        lr_note = (f"Detection: LR scores F1 = 1.0 on {det['lr_folds_f1_eq_1']}/{det['folds']} folds and 0.0 on fold(s) {zero}. "
                   "Fold means weight a 1-window fold the same as a 66-window fold.")
    render_html(f"""
    <div class="soc-card">
        <div class="soc-section-header"><div class="soc-section-title">LOEO 37-fold results (mean over folds, threshold 0.5)</div></div>
        <table>
            <thead><tr><th>Task</th><th>Model</th><th>F1</th><th>Precision</th><th>Recall</th><th>FPR</th><th>ROC-AUC</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
        <div style="font-family: 'Inter', sans-serif; font-size: 0.75rem; color: {t['text_muted']}; margin-top: 0.5rem;">{lr_note}</div>
    </div>
    """)

    # 2. Matched FPR on pooled test windows
    rows = ""
    for task, d in tasks.items():
        mf = d["matched_fpr"]
        for name, m in (("Stacked calibrated LSTM", mf["stacked"]), ("Logistic regression baseline", mf["lr"])):
            rows += (f"<tr><td>{task}</td><td>{name}</td><td><b>{_f(m['f1'], 3)}</b></td><td>{_f(m['precision'], 3)}</td>"
                     f"<td>{_f(m['recall'], 3)}</td><td>{_f(m['fpr'], 3)}</td><td>{_f(m['threshold'], 3)}</td></tr>")
    any_task = next(iter(tasks.values()))
    render_html(f"""
    <div class="soc-card" style="margin-top: 1rem;">
        <div class="soc-section-header"><div class="soc-section-title">Matched false-positive rate (~5%) on {any_task['matched_fpr']['test_windows']} pooled test windows</div></div>
        <table>
            <thead><tr><th>Task</th><th>Model</th><th>F1</th><th>Precision</th><th>Recall</th><th>FPR</th><th>Threshold</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
        <div style="font-family: 'Inter', sans-serif; font-size: 0.75rem; color: {t['text_muted']}; margin-top: 0.5rem;">{html.escape(any_task['matched_fpr']['note'])}</div>
    </div>
    """)

    # 3. History ablation + H* note
    rows = ""
    for task, d in tasks.items():
        ab = d["history_ablation_f1_at_0.5"]
        rows += "<tr><td>{}</td>{}</tr>".format(task, "".join(f"<td>{_f(ab.get(k), 3)}</td>" for k in ("normal", "permuted", "repeat_last", "lr_stage_only")))
    render_html(f"""
    <div class="soc-card" style="margin-top: 1rem;">
        <div class="soc-section-header"><div class="soc-section-title">What the gain comes from (F1 at 0.5, pooled test windows)</div></div>
        <table>
            <thead><tr><th>Task</th><th>Full model</th><th>History shuffled</th><th>History = last window repeated</th><th>Calibrated LR stage only</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
        <ul style="font-family: 'Inter', sans-serif; font-size: 0.78rem; color: {t['text_secondary']}; line-height: 1.6; margin: 0.5rem 0 0 1rem;">
            <li>Shuffling or removing the 30-window history does not change F1: the LSTM residual adds no measurable gain. The gain over the LR baseline comes from the stacked model's calibrated LR stage.</li>
            <li>{html.escape(val.get('h_star_note', ''))}</li>
            <li>{html.escape(val.get('lr_results_caveat', ''))}</li>
        </ul>
    </div>
    """)

    with st.expander("Per-fold F1 (stacked vs LR)"):
        for task, d in tasks.items():
            st.caption(f"{task} — target {d['target']}")
            st.dataframe(pd.DataFrame(d["per_fold"]), hide_index=True, width="stretch")

    # 4. Audit chain (real entries only)
    audit = get_audit_chain_status()
    notary = get_live_notarization_status()
    entries = audit.get("entries", [])[-5:]
    rows = "".join(
        f"<tr><td>{html.escape(str(e.get('index', '')))}</td><td>{html.escape(str(e.get('timestamp', '')))}</td>"
        f"<td>{html.escape(str(e.get('artifact_type', e.get('entry_type', ''))))}</td>"
        f"<td>{html.escape(str(e.get('description', '')))}</td>"
        f"<td><code>{html.escape(str(e.get('entry_hash', e.get('record_hash', '')))[:16])}</code></td></tr>"
        for e in reversed(entries)
    )
    issues = "; ".join(html.escape(str(i)) for i in audit.get("issues", [])) or "none"
    render_html(f"""
    <div class="soc-card" style="margin-top: 1rem;">
        <div class="soc-section-header"><div class="soc-section-title">Audit chain (backend/audit_chain.json)</div></div>
        <div style="font-family: 'JetBrains Mono', monospace; font-size: 0.78rem; color: {t['text_secondary']}; margin-bottom: 0.5rem;">
            Entries: {audit.get('length', 0)} &bull; Chain verifies: {'yes' if audit.get('is_valid') else 'no'} &bull; Issues: {issues}
            &bull; Notarization used by the last inference: {html.escape(str(notary.get('active_mechanism', 'none')))}
        </div>
        <table>
            <thead><tr><th>#</th><th>Timestamp</th><th>Type</th><th>Description</th><th>Hash</th></tr></thead>
            <tbody>{rows or '<tr><td colspan="5">No entries</td></tr>'}</tbody>
        </table>
    </div>
    """)

    # 5. Model file provenance (SHA-256 computed from the files on disk)
    rows = "".join(f"<tr><td><code>{p}</code></td><td><code>{_sha256(p)}</code></td></tr>" for p in PROVENANCE_FILES)
    render_html(f"""
    <div class="soc-card" style="margin-top: 1rem;">
        <div class="soc-section-header"><div class="soc-section-title">Model files used by inference</div></div>
        <table><thead><tr><th>File</th><th>SHA-256</th></tr></thead><tbody>{rows}</tbody></table>
        <div style="font-family: 'Inter', sans-serif; font-size: 0.75rem; color: {t['text_muted']}; margin-top: 0.4rem;">
            Plus 37 onset and 37 detection fold checkpoints in ml1/artifacts/lstm/lstm_stacked/; each carries its own PCA and LR scaler.
        </div>
    </div>
    """)


if __name__ == "__main__":
    render_page()
