"""
Cheap Graph-Derived Scalar Features Extractor
Uses the existing graph structure generated by GraphTopologyBuilder (stored in ucs_graph_edgelists.parquet)
to compute lightweight scalar graph features per window:
1. Degree Centrality (mean node degree in window)
2. Graph Density / Bipartite Clustering Signal
3. Degree Anomaly Score (backward-looking rolling deviation from recent baseline, zero lookahead leakage)
"""

from pathlib import Path
from typing import Optional
import numpy as np
import pandas as pd


def compute_scalar_graph_features(
    edgelist_path: Path | str,
    windows_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Computes scalar graph features per window and returns a DataFrame indexed by window_id.
    Ensures zero forward temporal leakage in rolling statistics.
    """
    edgelist_path = Path(edgelist_path)
    if not edgelist_path.exists():
        raise FileNotFoundError(f"Edgelists parquet not found at {edgelist_path}")

    df_edges = pd.read_parquet(edgelist_path)

    # 1. Window-level aggregations
    win_summary = df_edges.groupby("window_id").agg(
        total_edges=("dst_node_id", "count"),
        total_flows=("flow_count", "sum"),
        max_edge_flows=("flow_count", "max"),
        unique_src=("src_node_id", "nunique"),
        unique_dst=("dst_node_id", "nunique"),
    )

    # Total unique endpoints (nodes) per window
    nodes_per_win = df_edges.groupby("window_id").apply(
        lambda g: len(set(g["src_node_id"]).union(set(g["dst_node_id"]))),
        include_groups=False,
    )
    win_summary["total_nodes"] = nodes_per_win

    # Degree Centrality: average degree across active nodes in window
    win_summary["graph_degree_centrality"] = 2.0 * win_summary["total_edges"] / np.maximum(win_summary["total_nodes"], 1)

    # Community / Density signal: edge density and bipartite fan-in ratio
    win_summary["graph_density"] = win_summary["total_edges"] / np.maximum(
        win_summary["total_nodes"] * (win_summary["total_nodes"] - 1), 1
    )
    win_summary["graph_clustering_signal"] = win_summary["unique_dst"] / np.maximum(win_summary["unique_src"], 1)

    # Merge onto windows_df to preserve chronological ordering per episode/day
    base_df = windows_df[["window_id", "window_start_utc", "source_day"]].copy()
    merged = base_df.merge(
        win_summary[["graph_degree_centrality", "graph_density", "graph_clustering_signal", "total_edges"]],
        on="window_id",
        how="left",
    )
    # Fill windows with no recorded graph interaction with 0.0
    merged["graph_degree_centrality"] = merged["graph_degree_centrality"].fillna(0.0)
    merged["graph_density"] = merged["graph_density"].fillna(0.0)
    merged["graph_clustering_signal"] = merged["graph_clustering_signal"].fillna(0.0)
    merged["total_edges"] = merged["total_edges"].fillna(0.0)

    # Degree Anomaly Score:
    # Strictly backward-looking rolling z-score (window=10, min_periods=1) within each source_day
    # Z_t = (x_t - roll_mean_{t-1}) / (roll_std_{t-1} + epsilon)
    # Shifted by 1 window so current window does NOT leak into its own baseline!
    def calc_anomaly(series: pd.Series) -> pd.Series:
        shifted = series.shift(1)
        roll_mean = shifted.rolling(window=10, min_periods=1).mean()
        roll_std = shifted.rolling(window=10, min_periods=1).std().fillna(1.0)
        roll_std = np.maximum(roll_std, 1e-4)
        z = (series - roll_mean) / roll_std
        return z.fillna(0.0)

    merged["graph_degree_anomaly"] = merged.groupby("source_day")["graph_degree_centrality"].transform(calc_anomaly)

    graph_cols = [
        "graph_degree_centrality",
        "graph_density",
        "graph_clustering_signal",
        "graph_degree_anomaly",
    ]
    return merged[["window_id"] + graph_cols].set_index("window_id")


if __name__ == "__main__":
    ucs_win_path = Path("data-engineering/data/ucs/ucs_windows.parquet")
    edges_path = Path("data-engineering/data/ucs/ucs_graph_edgelists.parquet")
    win_df = pd.read_parquet(ucs_win_path).sort_values("window_start_utc").reset_index(drop=True)
    g_feats = compute_scalar_graph_features(edges_path, win_df)
    print("Graph features computed successfully:")
    print(g_feats.head(5))
    print("Summary statistics:")
    print(g_feats.describe())
