import os

report_content = """# Stage Head Classification Report — Honest Performance & Scoping Summary

> [!IMPORTANT]
> **EXECUTIVE SUMMARY & REAL CLASS-LEVEL PERFORMANCE**:
> - **Blended Metric Caveat**: The headline **86.01% LOEO overall accuracy** is a blended metric heavily dominated by the background `Unknown/Other` class (**285 of 386 samples = 73.8% base rate**).
> - **Effective Scope**: The stage head currently distinguishes **Credential Access vs. background** (Precision = 1.00, Recall = 0.573, F1 = 0.729, Support = 82). This represents genuine, validated signal.
> - **Complete Class Failure (Impact)**: All 19 test samples for **Impact** (from DDOS-LOIC-UDP) were **100% misclassified into Unknown/Other** (Precision = 0.00, Recall = 0.00, F1 = 0.00). The confusion matrix confirms 0 correct predictions for Impact.
> - **Zero-Support Classes**: Command & Control, Discovery, and Initial Access have **0 test support** in this 37-fold LOEO evaluation ($n=0$). There is currently no empirical evidence either way for these tactics.
> - **Claim Ladder Rung 4 Re-Scoping**: Claim Ladder Rung 4 ("stage trajectory from predicted state, all labelled windows") is strictly scoped to **"Credential Access vs. background"**, not "full ATT&CK stage classification".

---

## Architectural Verification
- **Input Verification**: Stage Head operates directly on **PREDICTED future latent state** $\hat{S}_{t+1}$ generated by `LSTMGaussianWorldModel` (Item 1 checkpoint), fulfilling strict architectural requirements.
- **ATT&CK Mapping Source**: `data/ucs/attack_tactics_mapping.yaml`
- **Unknown/Other Fallback Rule**: All benign or unmapped/low-confidence traffic windows default to `Unknown/Other`.
- **Scope Verification**: Evaluated across all labeled windows (Claim Ladder Rung 4). B1 stage transition (n=1 infiltration) is strictly excluded (case study scope owned by ML2).

---

## Performance Metrics — 37-Fold LOEO Protocol

- **LOEO Overall Blended Accuracy**: **0.8601** (Base rate = 73.83% Unknown/Other)
- **Total LOEO Evaluation Samples**: **386**

### 37-Fold LOEO Per-Class Performance
| Stage Tactic Class | Precision | Recall | F1-Score | Support | Status / Note |
|---|---|---|---|---|---|
| **Command and Control** | 0.0000 | 0.0000 | 0.0000 | 0 | No Test Support ($n=0$) |
| **Credential Access** | **1.0000** | **0.5732** | **0.7287** | **82** | **Validated Separation** |
| **Discovery** | 0.0000 | 0.0000 | 0.0000 | 0 | No Test Support ($n=0$) |
| **Impact** | **0.0000** | **0.0000** | **0.0000** | **19** | **Complete Failure (19/19 misclassified into Unknown/Other)** |
| **Initial Access** | 0.0000 | 0.0000 | 0.0000 | 0 | No Test Support ($n=0$) |
| **Unknown/Other** | 0.8407 | 1.0000 | 0.9135 | 285 | Background Base Rate Class |

### 37-Fold LOEO Confusion Matrix
```
True \ Pred             Command and   Credential A     Discovery        Impact  Initial Acce  Unknown/Othe
----------------------------------------------------------------------------------------------------------
Command and Control                0             0             0             0             0             0
Credential Access                  0            47             0             0             0            35
Discovery                          0             0             0             0             0             0
Impact                             0             0             0             0             0            19
Initial Access                     0             0             0             0             0             0
Unknown/Other                      0             0             0             0             0           285
```

---

## Chronological Split Evaluation (Single Final Test Window)

- **Chronological Split Accuracy**: **0.9164**
- **Unknown/Other Ratio in Test Split**: **91.64%** (285 of 311 test windows)

> [!WARNING]
> **CHRONOLOGICAL SPLIT ANNOTATION**:
> The chronological split test accuracy (91.64%) is **not distinguishable from the split's base rate given n=1 test window** (91.64% Unknown/Other). It does NOT provide independent confirming evidence of model performance and must not be cited as such in reports or presentations.

### Chronological Per-Class Metrics
| Stage Tactic Class | Precision | Recall | F1-Score | Support |
|---|---|---|---|---|
| **Command and Control** | 0.0000 | 0.0000 | 0.0000 | 26 |
| **Credential Access** | 0.0000 | 0.0000 | 0.0000 | 0 |
| **Discovery** | 0.0000 | 0.0000 | 0.0000 | 0 |
| **Impact** | 0.0000 | 0.0000 | 0.0000 | 0 |
| **Initial Access** | 0.0000 | 0.0000 | 0.0000 | 0 |
| **Unknown/Other** | 0.9164 | 1.0000 | 0.9564 | 285 |

---

## Technical Hypotheses for Impact Class Failure

1. **Low Cross-Fold Training Volume**: Impact samples (originating from DDOS-LOIC-UDP traffic) comprise only 19 test windows across all 37 LOEO folds. Across the LOEO training splits, the low positive support for Impact provides insufficient loss gradient relative to the overwhelming background class.
2. **Latent Representation Overlap**: The latent feature representation $\\hat{S}_{t+1}$ generated by the world model for short UDP flood bursts in DDOS-LOIC-UDP closely resembles background network noise, leading the linear stage head to assign higher probability to the prior class (`Unknown/Other`).

*Note: These are hypotheses based on sample distribution analysis, not confirmed mechanisms.*
"""

output_path = "artifacts/lstm/stage_head/stage_head_report.md"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(report_content)

print(f"Successfully updated {output_path} with honest stage head reporting.")
